### ISSUE TITLE
Conscious Language Changes

### ISSUE THREAD

**Issue by srijan-sivakumar** [gluster/glusterdocs#619]
Creating an issue to track the conscious language changes to be done in the glusterdocs repository.

**Comment by srijan-sivakumar** [comment]
@sankarshanmukhopadhyay , can we start with renaming of the master branch to devel or something in line with that. I'm working on changing the terminologies related to geo-replication which will be in sync with the efforts put in by Ravi at glusterfs repo.

**Comment by sankarshanmukhopadhyay** [comment]
> @sankarshanmukhopadhyay , can we start with renaming of the master branch to devel or something in line with that. I'm working on changing the terminologies related to geo-replication which will be in sync with the efforts put in by Ravi at glusterfs repo.

@amarts - considering the suggestion above, I was thinking more in terms of 'main' rather than 'devel'. The latter tends to imply a constant stream of changesets and some form of instability. Do you have any strong preference between devel and main or have a better alternative? We'll also need to figure out the impact of this renaming - whether publication toolchain and other references will break and need fixing.

**Comment by amarts** [comment]
Lets go ahead with `main`, which is what git is defaulting to.
